# Generated by Django 3.2.4 on 2021-06-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('sur_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('adharnum', models.IntegerField(blank=True, null=True)),
                ('mobilenum', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(max_length=20)),
                ('cgpa', models.IntegerField(blank=True, null=True)),
                ('rank', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
